syntax = "proto3";

package jdplus.main.ws;

/* Frequency of an event. Only regular frequencies higher or equal to yearly frequency are considered. */
enum Frequency {
  /* Undefined frequency. To be used when the frequency of an event is unknown. */
  FREQ_UNDEFINED = 0;
  /* One event by year */
  FREQ_YEARLY = 1;
  /* One event every half-year */
  FREQ_HALF_YEARLY = 2;
  /* One event every four months */
  FREQ_QUADRI_MONTHLY = 3;
  /* One event every quarter */
  FREQ_QUARTERLY = 4;
  /* One event every two months */
  FREQ_BI_MONTHLY = 6;
  /* One event every month */
  FREQ_MONTHLY = 12;
  /* One event every day */
  FREQ_DAILY = 365;
}

message DateDto {
  // Year of the date. Must be from 1 to 9999
  int32 year = 1;

  // Month of a year. Must be from 1 to 12, or 0 to specify a year without a
  // month and day.
  int32 month = 2;

  // Day of a month. Must be from 1 to 31 and valid for the year and month, or 0
  // to specify a year by itself or a year and month where the day isn't
  // significant.
  int32 day = 3;
}

message TsPeriodDto {
  Frequency frequency = 1;
  int32 year = 2;
  // position in the year (from 0 to annual_frequency excluded)
  int32 pos = 3;
}

message TsDataDto {
  TsPeriodDto start = 1;
  repeated double values = 2;
}

message MatrixDto {
  int32 nrows = 1;
  int32 ncols = 2;
  // The number of values should be nrows*ncols. Values are organized by columns (1st columnn, 2nd column...)
  repeated double values = 3;
}

message TsMatrixDto {
  TsPeriodDto start = 1;
  MatrixDto values = 2;
}

message TsMonikerDto {
  string source = 1;
  string id = 2;
}

message TsDto {
  string name = 1;
  TsMonikerDto moniker = 2;
  TsDataDto data = 3;
  map<string, string> metadata = 4;
}

// Observation defined on a calendar period
message TsObservationDto {
  // For point observations, start should be equal to end
  // Otherwise, start is included in and end is excluded from the period corresponding to the observation
  DateDto start = 1;
  DateDto end = 2;
  double value = 3;
}

message TimeSeriesDto {
  string name = 1;
  TsMonikerDto moniker = 2;
  repeated TsObservationDto observations = 3;
  map<string, string> metadata = 4;
}

enum SelectionType {
  SPAN_ALL = 0;
  SPAN_FROM = 1;
  SPAN_TO = 2;
  SPAN_BETWEEN = 3;
  SPAN_LAST = 4;
  SPAN_FIRST = 5;
  SPAN_EXCLUDING = 6;
  SPAN_NONE = 7;
}

message TimeSelectorDto {
  SelectionType type = 1;
  int32 n0 = 2;
  int32 n1 = 3;
  DateDto d0 = 4;
  DateDto d1 = 5;
}

enum ResultStatusType {
  STATUS_OK = 0;
  STATUS_ERROR = 1;
  STATUS_WARNING = 2;
}

message ResultStatusDto {
  ResultStatusType type = 1;
  string message = 2;
}

/* Default input of TsFunctions (no additional parameter) */
message TsFunctionInputDto {
  string id = 1;
  TsDataDto series = 2;
}

/* Default output of TsFunctions (no additional output) */
message TsFunctionOutputDto {
  string id = 1;
  ResultStatusDto status = 2;
  TsDataDto series = 3;
}

/* Computes the percentage of variation (=[y(t)/y(t-lag)-1]*100) */
message PctInputDto {
  string id = 1;
  TsDataDto series = 2;
  int32 lag = 3;
}

/* Apply <power> times the difference operator (y[t]-y[t-lag]) */
message DeltaInputDto {
  string id = 1;
  TsDataDto series = 2;
  int32 lag = 3;
  int32 power = 4;
}


enum AggregationType {
  AGGREGATION_NONE = 0;
  AGGREGATION_SUM = 1;
  AGGREGATION_AVERAGE = 2;
  AGGREGATION_FIRST = 3;
  AGGREGATION_LAST = 4;
  AGGREGATION_MAX = 5;
  AGGREGATION_MIN = 6;
}

message AggregationInputDto {
  string id = 1;
  TsDataDto series = 2;
  AggregationType aggregation_type = 3;
  Frequency new_frequency = 4;
  // only complete periods (all the months in the year...) are computed
  bool complete = 5;
}

message HodrickPrescottInputDto {
  string id = 1;
  TsDataDto series = 2;
  int32 lambda = 3;
}

message HodrickPrescottOutputDto {
  string id = 1;
  ResultStatusDto status = 2;
  TsDataDto trend = 3;
  TsDataDto noise = 4;
}

message DescriptiveStatisticsDto {

  string id = 1;
  ResultStatusDto status = 2;
  int32 n = 3;
  int32 nmissing = 4;
  double max = 5;
  double min = 6;
  double average = 7;
  double stdev = 8;
  double q25 = 10;
  double q50 = 11;
  double q75 = 12;
}

/* Parameters used when collecting observations in order to create time series. */
message ObsGatheringDto {
  Frequency frequency = 1;
  AggregationType aggregation_type = 2;
  bool allow_partial_aggregation = 3;
  bool include_missing_values = 4;
}

message BuildTsDataObsDto {
  DateDto date = 1;
  double value = 2;
}

message BuildTsDataInputDto {
  string id = 1;
  ObsGatheringDto gathering = 2;
  repeated BuildTsDataObsDto observations = 3;
}

enum DistributionType {
  DIST_FIRST = 0;
  DIST_LAST = 1;
  DIST_MIDDLE = 2;
}

message BuildTsDataTableInputDto {
  string id = 1;
  DistributionType distribution_type = 2;
  repeated TsDataDto collection = 3;
}

enum ValueStatus {
  VS_PRESENT = 0;
  VS_UNUSED = 1;
  VS_BEFORE = 2;
  VS_AFTER = 3;
  VS_EMPTY = 4;
}

message BuildTsDataTableOutputDto {
  string id = 1;
  TsMatrixDto matrix = 2;
  repeated ValueStatus statuses = 3;
}

message TemporalDisaggregationResultsDto {
  TsDataDto originalSeries = 1;
  TsDomainDto disaggregationDomain = 2;
  // Regression variables
  repeated TsVariableDto indicators = 3;
  // Regression estimation. The order correspond to the order of the variables.
  int32 hyperParametersCount = 4;
  DiffuseConcentratedLikelihoodDto likelihood = 5;
  DiffuseLikelihoodStatisticsDto stats = 6;
  ObjectiveFunctionPointDto maximum = 7;
  ResidualsDiagnosticsDto residualsDiagnostics = 8;
  TsDataDto disaggregatedSeries = 9;
  TsDataDto stDevDisaggregatedSeries = 10;
  TsDataDto regressionEffects = 11;
}

message DiffuseConcentratedLikelihoodDto {
  double ll = 1;
  double ssqerr = 2;
  double ldet = 3;
  double lddet = 4;
  int32 nobs = 5;
  int32 nd = 6;
  int32 nxd = 7;
  repeated double res = 8;
  repeated double b = 9;
  MatrixDto bvar = 10;
  bool legacy = 11;
  bool scalingFactor = 12 ;
}

message TsVariableDto {
  string name = 1;
  string id = 2;
  int32 lag = 3;
  ParameterDto coefficient = 4;
  map<string, string> metadata = 5;
}

enum ParameterType{
  // Similar to null
  PARAMETER_UNUSED = 0;
  // Parameter is used but not defined (to be estimated)
  PARAMETER_UNDEFINED = 1;
  PARAMETER_FIXED = 2;
  PARAMETER_INITIAL = 3;
  PARAMETER_ESTIMATED = 4;
}

message ParameterDto {
  double value = 1;
  ParameterType type = 2;
  string description = 3;
}

message DiffuseLikelihoodStatisticsDto {
  int32 nobs = 1;
  int32 ndiffuse = 2;
  int32 nparams = 3;
  int32 degrees_of_freedom = 4;
  double log_likelihood = 5;
  double adjusted_log_likelihood = 6;
  double aic = 7;
  double aicc = 8;
  double bic = 9;
  double ssq = 13;
  double ssqerr = 14;
  double ldet = 15;
  double dcorrection = 16;
}

message TsDomainDto {
  TsPeriodDto startPeriod = 1;
  int32 length = 2;
}

message ObjectiveFunctionPointDto {
  double value = 1;
  repeated double parameters = 2;
  repeated double gradient = 3;
  MatrixDto hessian = 4;
}

message ResidualsDiagnosticsDto {
  TsDataDto fullResiduals = 1;
  NiidTestsDto niid = 2;
}

message NiidTestsDto {
  /* Normality */
  StatisticalTestDto mean = 1;
  StatisticalTestDto skewness = 2;
  StatisticalTestDto kurtosis = 3;
  StatisticalTestDto doornik_hansen = 4;

  /* Independence */
  StatisticalTestDto ljung_box = 5;
  StatisticalTestDto box_pierce = 6;
  StatisticalTestDto seasonal_ljung_box = 7;
  StatisticalTestDto seasonal_box_pierce = 8;

  /* Randomness */
  StatisticalTestDto runs_number = 9;
  StatisticalTestDto runs_length = 10;
  StatisticalTestDto up_down_runs_number = 11;
  StatisticalTestDto up_down_runs_length = 12;

  /* Linearity */
  StatisticalTestDto ljung_box_on_squares = 13;
  StatisticalTestDto box_pierce_on_squares = 14;
}

message StatisticalTestDto{
  double value = 1;
  double pValue = 2;
  string description = 3;
}

message TemporalDisaggregationRequestDto {
  TsDataDto y = 1;
  bool constant = 2;
  bool trend = 3;
  repeated TsDataDto indicators = 4;
  string model = 5;
  bool average = 6;
  double rho = 7;
  bool fixedRho = 8;
  double truncatedRho = 9;
  bool zeroInit = 10;
  string algorithm = 11;
  bool diffuserEgs = 12;
}